set_doorbell_message:
  name: Set Doorbell message
  description: >
    Use to dynamically set the message on a Doorbell LCD screen. Should only be used to set dynamic messages
    (i.e. setting the current outdoor temperature on your Doorbell). Static messages should still using the Select entity and the
    add_doorbell_text / remove_doorbell_text services.
  fields:
    entity_id:
      name: Doorbell Text
      description: (Required) Doorbell to display message on
      example: "select.front_doorbell_camera_doorbell_text"
      required: true
      selector:
        entity:
          integration: unifiprotect
          domain: select
          device_class: unifiprotect__lcd_message
    message:
      name: Message to display
      description: (Required) Message to display on LCD Panel. Max 30 characters
      example: "Welcome | 09:23 | 25°C"
      required: true
      selector:
        text:
    duration:
      name: Duration (minutes)
      description: "(Optional) Number of minutes to display message, before returning to default. Leave blank to display always"
      example: 5
      selector:
        number:
          min: 1
          max: 120
          step: 1
          mode: slider
